/***********************************************************************************************
** 文件:    AppVer.h
**
** 说明:    应用程序版本定义
**
** 作者:    Jun
**
** 时间:    2010-8-20(创建)
***********************************************************************************************/
#ifndef  ApplicationVersionFileH
#define  ApplicationVersionFileH

#define  ApplicationVersionMajor        0
#define  ApplicationVersionMinor        0
#define  ApplicationVersionMinor2       0

#define  ApplicationVersionString      "0.0.0"

#define  ApplicationBuiltDate          "2010/8/20"

#endif
/*----------------------------------------------------------------------------------------------
 *                   作者
 * 
 * Name:  Jun
 * Email: FamesOS@126.com
**--------------------------------------------------------------------------------------------*/

/*
*本文件结束: AppVer.h ==========================================================================
*/

